version: "3.2"

networks:
  web-app-network:
    driver: bridge
services:
  web-app:
    build: .
    ports:
      - "8123:80"
    volumes:
      - "./src:/var/www/html"
    container_name: "web-app-8123"
    networks:
      - web-app-network

  open-ldap:
    image: bitnami/openldap:2.5.14-debian-11-r1@sha256:fda11bb8d89767889050aeadf8a17edfa02db8b9b4b2f4df065d0dfa40862de9
    ports:
      - '1389:1389'
      - '1636:1636'
    volumes:
      - './openldap_data:/bitnami/open-ldap'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - web-app-network

  db:
    image: mysql:5.7.40-debian@sha256:d9c40d31d0d3e075e4f13b1d6466b6cc95e57e27d9e88969143afc39d435d699
    ports:
      - '3309:3306'
    volumes:
      - './openldap_data:/bitnami/open-ldap'
    environment:
      - MYSQL_ROOT_PASSWORD=ANSKk08aPEDbFjDO
      - MYSQL_DATABASE=testing_app
      - MYSQL_USER=web_admin
      - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - web-app-network