version: "3.2"

networks:
  web-app-network:
    driver: bridge
services:
  web-app:
    build: .
    ports:
      - "8123:80"
    volumes:
      - "./src:/var/www/html"
    container_name: "web-app-8123"
    networks:
      - web-app-network

  open-ldap:
    image: bitnami/openldap:2.5.14-debian-11-r1@sha256:fda11bb8d89767889050aeadf8a17edfa02db8b9b4b2f4df065d0dfa40862de9
    ports:
      - '1389:1389'
      - '1636:1636'
    volumes:
      - './openldap_data:/bitnami/open-ldap'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - web-app-network